---
version: 2
project_name: tab-commit
release:
  github:
    owner: devinjeon
    name: tab-commit
builds:
  - id: tab-commit
    main: ./cmd
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: ['-X main.version={{ .Tag }}']
    binary: tab-commit
archives:
  - id: tab-commit
    files: [scripts/*]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats:
          - zip
    # 'replacements:' is deprecated.
    # Use Go template logic within 'name_template' instead.
    name_template: '{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{
      else }}{{ .Arch }}{{ end }}'
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha256
brews:
  - name: tab-commit
    commit_author:
      name: Hyojun Jeon
      email: jeon@hyojun.me
    description: tab-commit is a simplest way to generate commit messages — just press
      `<Tab>` after `git commit -m`.
    homepage: https://github.com/devinjeon/tab-commit
    # TODO(devinjeon)
    # install: |
    #   bin.install "tab-commit"
    #   zsh_completion.install "scripts/tab-commit-completion.zsh" => "_tab-commit"
    #   bash_completion.install "scripts/tab-commit-completion.bash" => "tab-commit"
    repository:
      owner: devinjeon
      name: tab-commit
      pull_request:
        enabled: true
