---
version: 2
project_name: tab-commit-gpt
release:
  github:
    owner: devinjeon
    name: tab-commit-gpt
builds:
  - id: tab-commit-gpt
    main: ./cmd
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: ['-X main.version={{ .Tag }}']
    binary: tab-commit-gpt
archives:
  - id: tab-commit-gpt
    files: [scripts/*]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats:
          - zip
    # 'replacements:' is deprecated.
    # Use Go template logic within 'name_template' instead.
    name_template: '{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{
      else }}{{ .Arch }}{{ end }}'
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha256
brews:
  - name: tab-commit-gpt
    commit_author:
      name: Hyojun Jeon
      email: jeon@hyojun.me
    description: tab-commit-gpt is a simplest way to generate commit messages — just
      press `<Tab>` after `git commit -m`.
    homepage: https://github.com/devinjeon/tab-commit-gpt
    repository:
      owner: devinjeon
      name: tab-commit-gpt
      pull_request:
        enabled: true
    install: |
      bin.install "tab-commit-gpt"
      bin.install "scripts/tab-commit-gpt.sh"
    post_install: |
      zshrc = File.expand_path("~/.zshrc")
      script_line = "source \"#{HOMEBREW_PREFIX}/opt/tab-commit-gpt/scripts/tab-commit-gpt.sh\""
      if File.writable?(zshrc)
        content = File.read(zshrc) rescue ""
        unless content.include?(script_line)
          File.open(zshrc, "a") do |f|
            f.puts "\n# Added by tab-commit-gpt"
            f.puts script_line
          end
          ohai "Added tab-commit-gpt to ~/.zshrc"
        end
      else
        opoo "~/.zshrc is not writable. Please run the following command to add tab-commit-gpt to your .zshrc:"
        puts
        puts "  echo '#{script_line}' >> ~/.zshrc"
      end
    caveats: |-
      To use tab-commit-gpt, add the following line to your .zshrc:

      $ echo "source \"$(brew --prefix tab-commit-gpt)/scripts/tab-commit-gpt.sh\"" >> ~/.zshrc
