# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TabCommitGpt < Formula
  desc "tab-commit-gpt is a simplest way to generate commit messages — just press `<Tab>` after `git commit -m`."
  homepage "https://github.com/devinjeon/tab-commit-gpt"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.2.0/tab-commit-gpt_v0.2.0_darwin_x86_64.tar.gz"
      sha256 "24807f506a86288deb9781808da1bf980150b93297d4e04e42f125b68b2c11f4"

      def install
        bin.install "tab-commit-gpt"
        etc.install "scripts/tab-commit-gpt.zsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.2.0/tab-commit-gpt_v0.2.0_darwin_arm64.tar.gz"
      sha256 "5e1259d9d08ef6eccc62628c2186a428d8b7a101388fee9dc68e5465e8818ef9"

      def install
        bin.install "tab-commit-gpt"
        etc.install "scripts/tab-commit-gpt.zsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.2.0/tab-commit-gpt_v0.2.0_linux_x86_64.tar.gz"
        sha256 "8ef170e7e37378874cacc5440a2513d9268b1302e22da87105678c5410207f7f"

        def install
          bin.install "tab-commit-gpt"
          etc.install "scripts/tab-commit-gpt.zsh"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.2.0/tab-commit-gpt_v0.2.0_linux_arm64.tar.gz"
        sha256 "07ac632db7795faf99e8003568420232c1180a16f0719a5db9552e0364b58a1c"

        def install
          bin.install "tab-commit-gpt"
          etc.install "scripts/tab-commit-gpt.zsh"
        end
      end
    end
  end

  def post_install
    zshrc = File.expand_path("~/.zshrc")
    script_line = "source \"#{HOMEBREW_PREFIX}/etc/tab-commit-gpt.zsh\""
    ohai "===== [!!! 🚀 ACTION REQUIRED !!!] ====="
    ohai "Please run the following command to add tab-commit-gpt to your .zshrc:"
    puts
    puts "  echo '#{script_line}' >> ~/.zshrc"
    ohai "========================================"
  end
end
