# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TabCommitGpt < Formula
  desc "tab-commit-gpt is a simplest way to generate commit messages — just press `<Tab>` after `git commit -m`."
  homepage "https://github.com/devinjeon/tab-commit-gpt"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.1.0/tab-commit-gpt_v0.1.0_darwin_x86_64.tar.gz"
      sha256 "92ad48f8f637fac5e07aa9aa40d74e82bc6c26c3368c50d0ff726c4f30dbad2c"

      def install
        bin.install "tab-commit-gpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.1.0/tab-commit-gpt_v0.1.0_darwin_arm64.tar.gz"
      sha256 "2bff040cb3bcf3c7e2e480aeb655ab86150184500b107b0a0d5d89eaa1e2a812"

      def install
        bin.install "tab-commit-gpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.1.0/tab-commit-gpt_v0.1.0_linux_x86_64.tar.gz"
        sha256 "ab850ff74f0bd38005b0359777e0a8eb9d5c5a696f6ced8695768d764dae9294"

        def install
          bin.install "tab-commit-gpt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devinjeon/tab-commit-gpt/releases/download/v0.1.0/tab-commit-gpt_v0.1.0_linux_arm64.tar.gz"
        sha256 "7a5e6d7636d56423a902833afff7c871f83872b3cd48ef4c5e1675b54adf8b59"

        def install
          bin.install "tab-commit-gpt"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use tab-commit-gpt, add the following line to your .zshrc:

      $ echo "source \"$(brew --prefix tab-commit-gpt)/scripts/tab-commit-gpt.sh\"" >> ~/.zshrc
    EOS
  end
end
